### ISSUE TITLE
Demo crashes on current godot tip 

### ISSUE THREAD

**Issue by capnm** [BastiaanOlij/gdprocmesh#23]
Just FYI, maybe something needs updating …

compile godot3 tip https://github.com/godotengine/godot/commit/29f2571662da0ee93ea2a632ec3b60aa26246563

```bash
cd gdprocmesh
git log -1
commit 7b4537817fac388376c44352cfd8748ab07733b9 (HEAD -> master, origin/master, origin/HEAD)
Author: Bastiaan Olij <mux213@gmail.com>
Date:   Thu Aug 30 21:44:26 2018 +1000

    Added a ground plane

git submodule update
godot3 --gdnative-generate-json-api api.json

cd godot-cpp
scons platform=x11 generate_bindings=yes use_custom_api_file=yes custom_api_file=../api.json

cd ..
scons platform=linux

cd demo
godot3 -e
```

```
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:997.
ERROR: _load: Failed loading resource: res://.import/window01.obj-5c85cf881c5e79c77eaca22190b2a88e.mesh
   At: core/io/resource_loader.cpp:190.
ERROR: _load: Failed loading resource: res://Examples/window01.obj
   At: core/io/resource_loader.cpp:190.
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:997.
ERROR: _load: Failed loading resource: res://.import/window01.obj-5c85cf881c5e79c77eaca22190b2a88e.mesh
   At: core/io/resource_loader.cpp:190.
ERROR: _load: Failed loading resource: res://Examples/window01.obj
   At: core/io/resource_loader.cpp:190.
WARNING: _parse_ext_resource: Couldn't load external resource: res://Examples/window01.obj
   At: scene/resources/scene_format_text.cpp:174.

Thread 1 "godot3" received signal SIGSEGV, Segmentation fault.
Object::get_script_instance_binding () at core/object.cpp:1918
1918		if (!_script_instance_bindings[p_script_language_index]) {


(gdb) l
1913		//it's up to the script language to make this thread safe, if the function is called twice due to threads being out of syncro
1914		//just return the same pointer.
1915		//if you want to put a big lock in the entire function and keep allocated pointers in a map or something, feel free to do it
1916		//as it should not really affect performance much (won't be called too often), as in far most caes the condition below will be false afterwards
1917	
1918		if (!_script_instance_bindings[p_script_language_index]) {
1919			void *script_data = ScriptServer::get_language(p_script_language_index)->alloc_instance_binding_data(this);
1920			if (script_data) {
1921				atomic_increment(&instance_binding_count);
1922				_script_instance_bindings[p_script_language_index] = script_data;


(gdb) bt
#0  Object::get_script_instance_binding () at core/object.cpp:1918
#1  0x0000555555b26a5d in NativeScriptLanguage::get_instance_binding_data () at modules/gdnative/nativescript/nativescript.cpp:1310
#2  0x00007fffe0820fd9 in godot::Mesh::___get_from_variant (a=...) at godot-cpp/include/gen/Mesh.hpp:23
#3  godot::Ref<godot::Mesh>::Ref (p_variant=..., this=0x7fffffffc1e0) at godot-cpp/include/core/Ref.hpp:159
#4  godot::GDProcInMesh::set_input (this=this@entry=0x55555e843f10, p_input=...) at src/input/gdprocinmesh.cpp:85
#5  0x00007fffe081a83c in godot::GDProcMesh::_set (this=<optimized out>, p_name=..., p_value=...) at src/gdprocmesh.cpp:153
#6  0x00007fffe081c79d in godot::_WrappedMethod<godot::GDProcMesh, bool, godot::String, godot::Variant>::apply<0, 1> (args=<optimized out>, obj=<optimized out>, 
    ret=0x7fffffffc440, this=<optimized out>) at godot-cpp/include/core/Godot.hpp:196
#7  godot::__wrapped_method<godot::GDProcMesh, bool, godot::String, godot::Variant> (method_data=<optimized out>, user_data=<optimized out>, num_args=<optimized out>, 
    args=<optimized out>) at godot-cpp/include/core/Godot.hpp:223
#8  0x0000555555b2aae8 in NativeScriptInstance::set () at modules/gdnative/nativescript/nativescript.cpp:584
#9  0x0000555557750c5c in Object::set () at core/object.cpp:413
#10 0x000055555709693f in ResourceInteractiveLoaderText::poll () at scene/resources/scene_format_text.cpp:598
#11 0x000055555795c242 in ResourceFormatLoader::load () at core/io/resource_loader.cpp:142
#12 0x000055555795babb in ResourceLoader::_load () at core/io/resource_loader.cpp:177
#13 0x000055555795bde0 in ResourceLoader::load () at core/io/resource_loader.cpp:219
#14 0x00005555570961b9 in ResourceInteractiveLoaderText::poll () at scene/resources/scene_format_text.cpp:432
#15 0x000055555795c242 in ResourceFormatLoader::load () at core/io/resource_loader.cpp:142
#16 0x000055555795babb in ResourceLoader::_load () at core/io/resource_loader.cpp:177
#17 0x000055555795bde0 in ResourceLoader::load () at core/io/resource_loader.cpp:219
#18 0x00005555570961b9 in ResourceInteractiveLoaderText::poll () at scene/resources/scene_format_text.cpp:432
#19 0x000055555795c242 in ResourceFormatLoader::load () at core/io/resource_loader.cpp:142
#20 0x000055555795babb in ResourceLoader::_load () at core/io/resource_loader.cpp:177
#21 0x000055555795bde0 in ResourceLoader::load () at core/io/resource_loader.cpp:219
#22 0x00005555561008eb in EditorNode::load_scene () at editor/editor_node.cpp:2817
#23 0x0000555556101870 in EditorNode::_sources_changed () at editor/editor_node.cpp:549
#24 0x000055555592e8b4 in MethodBind1<bool>::call () at core/method_bind.gen.inc:729
#25 0x00005555577434fc in Object::call () at core/object.cpp:968
#26 0x000055555774f7db in Object::emit_signal () at core/object.cpp:1254
#27 0x0000555557750825 in Object::emit_signal () at core/object.cpp:1307
#28 0x000055555609964e in EditorFileSystem::_notification () at editor/editor_file_system.cpp:1074
#29 0x0000555557740804 in Object::notification () at core/object.cpp:978
#30 0x0000555556903018 in SceneTree::_notify_group_pause () at scene/main/scene_tree.cpp:957
#31 0x0000555556905bf4 in SceneTree::idle () at scene/main/scene_tree.cpp:510
#32 0x00005555557942c4 in Main::iteration () at main/main.cpp:1800
#33 0x000055555577d9b1 in OS_X11::run () at platform/x11/os_x11.cpp:2785
#34 0x000055555576f42c in main () at platform/x11/godot_x11.cpp:55


(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7faa800 (LWP 1169) "godot3" Object::get_script_instance_binding () at core/object.cpp:1918
  2    Thread 0x7ffff7fa9700 (LWP 1174) "godot3" 0x00007ffff5f776d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x555558f15168)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fffe9d13700 (LWP 1175) "amdgpu_cs:0" 0x00007ffff5f749f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555559027624)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  4    Thread 0x7fffe8fb3700 (LWP 1176) "disk_cache:0" 0x00007ffff5f749f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55555902b818)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  5    Thread 0x7fffe3df5700 (LWP 1177) "si_shader:0" 0x00007ffff5f749f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5555590305dc)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  6    Thread 0x7fffe35f4700 (LWP 1178) "si_shader_low:0" 0x00007ffff5f749f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5555590306e8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  7    Thread 0x7fffe2df3700 (LWP 1179) "gallium_drv:0" 0x00007ffff5f749f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5555590e5ae4)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  8    Thread 0x7fffe8699700 (LWP 1180) "godot3" 0x00007ffff5f776d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5555591564b8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  9    Thread 0x7fffe82b6700 (LWP 1181) "godot3" 0x00007ffff5f78c60 in __GI___nanosleep (requested_time=0x7fffe82b5d70, remaining=0x7fffe82b5d70)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  10   Thread 0x7fffe8275700 (LWP 1182) "godot3" 0x00007ffff51129d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffe8274d60, 
    remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  11   Thread 0x7fffe20b9700 (LWP 1183) "godot3" 0x00007ffff5f78c60 in __GI___nanosleep (requested_time=0x7fffe20b8c00, remaining=0x7fffe20b8c00)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  12   Thread 0x7fffe2058700 (LWP 1184) "godot3" 0x00007ffff5f776d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55555a7c0b58)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  13   Thread 0x7fffe2572700 (LWP 1185) "godot3" 0x00007ffff5f78c60 in __GI___nanosleep (requested_time=0x7fffe2571d80, remaining=0x7fffe2571d80)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28


```

**Comment by BastiaanOlij** [comment]
> ERROR: _load: Failed loading resource: res://Examples/window01.obj
>    At: core/io/resource_loader.cpp:190.
> WARNING: _parse_ext_resource: Couldn't load external resource: res://Examples/window01.obj
>    At: scene/resources/scene_format_text.cpp:174.

Looks like it's crashing because window01.obj is not loaded, which makes sense because .obj is filtered out because on Windows those are binaries output by the compiler.
Wavefront just happens to use .obj as an extension too :)

Anyway I've just added it and committed it, hopefully it will prevent the crash..

**Comment by capnm** [comment]
I didn't realize it was not there :-)
